# Generated by Django 5.0.7 on 2024-07-31 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logins',
            options={'managed': True},
        ),
    ]
